feat: workflow beta version support (#1279)

diff --git a/.github/workflows/prepare-release.yml b/.github/workflows/prepare-release.yml
--- a/.github/workflows/prepare-release.yml
+++ b/.github/workflows/prepare-release.yml
@@ -10,11 +10,14 @@ on:
         default: 'minor'
         type: choice
         options:
-          - 'minor'
-          - 'hotfix'
-          - 'rc'
+          - "minor"
+          - "hotfix"
+          - "rc"
+          - "beta"
       RELEASE_CANDIDATE_VERSION:
-        description: 'Release candidate version (e.g. 15.0.0.rc.0)'
+        description: "Release candidate version (e.g. 15.0.0-rc.0)"
+      BETA_VERSION:
+        description: "Beta version (e.g. 15.0.0-beta.0)"
 
 env:
   NPM_REGISTRY: https://registry.npmjs.org/
@@ -37,23 +40,33 @@ jobs:
             isHotfix=1
             isMinor=0
             isRC=0
+            isBeta=0
           elif [ "${{ github.event.inputs.RELEASE_TYPE }}" = "rc" ]; then
             BASELINE_BRANCH=${{ env.DEVELOP_BRANCH }}
             isHotfix=0
             isMinor=0
             isRC=1
+            isBeta=0
+          elif [ "${{ github.event.inputs.RELEASE_TYPE }}" = "beta" ]; then
+            BASELINE_BRANCH=${{ env.DEVELOP_BRANCH }}
+            isHotfix=0
+            isMinor=0
+            isRC=0
+            isBeta=1
           else
             BASELINE_BRANCH=${{ env.DEVELOP_BRANCH }}
             isHotfix=0
             isMinor=1
             isRC=0
+            isBeta=0
           fi
           echo "BASELINE_BRANCH=$BASELINE_BRANCH" >> $GITHUB_ENV
           echo "isHotfix=$isHotfix" >> $GITHUB_OUTPUT
           echo "isMinor=$isMinor" >> $GITHUB_OUTPUT
           echo "isRC=$isRC" >> $GITHUB_OUTPUT
+          echo "isBeta=$isBeta" >> $GITHUB_OUTPUT
 
-      - name: Setup release candidate
+      - name: Setup release candidate version
         if: ${{ steps.parameters.outputs.isRC == true }}
         id: release-candidate
         run: |
@@ -62,6 +75,18 @@ jobs:
             echo "version=${BASH_REMATCH[0]}" >> $GITHUB_OUTPUT
           else
             echo "Invalid Release Candidate version"
+            exit 1
+          fi
+
+      - name: Setup Beta version
+        if: ${{ steps.parameters.outputs.isBeta == true }}
+        id: beta
+        run: |
+          versionNumber=${{ github.event.inputs.BETA_VERSION}}
+          if [[ $versionNumber =~ ^[0-9]+\.[0-9]+\.[0-9]+\-beta\.[0-9]+ ]]; then
+            echo "version=${BASH_REMATCH[0]}" >> $GITHUB_OUTPUT
+          else
+            echo "Invalid Beta version"
             exit 1
           fi
 
@@ -117,6 +142,21 @@ jobs:
           version=$(echo "${{ steps.release-candidate.outputs.version }}")
           npm version $version --no-git-tag-version
 
+      ## Beta
+      - name: bumping minor version in package.json
+        if: ${{ steps.parameters.outputs.isBeta == true }}
+        run: |
+          version=$(echo "${{ steps.beta.outputs.version }}")
+          npm version $version --no-git-tag-version
+          echo "RELEASE_VERSION=$(node -pe "require('./package.json')['version']")" >> $GITHUB_ENV
+
+      - name: bumping minor version in internal package.json
+        if: ${{ steps.parameters.outputs.isBeta == true }}
+        working-directory: ${{ env.LIBRARY_PATH }}
+        run: |
+          version=$(echo "${{ steps.beta.outputs.version }}")
+          npm version $version --no-git-tag-version
+
       ## HOTFIX
       - name: bumping hotfix version in package.json
         if: ${{ steps.parameters.outputs.isHotfix == true }}
@@ -131,7 +171,7 @@ jobs:
           npm version patch --no-git-tag-version
 
       - name: Create release branch
-        if: ${{ steps.parameters.outputs.isMinor == true }} || ${{ steps.parameters.outputs.isRC == true }}
+        if: ${{ steps.parameters.outputs.isMinor == true }} || ${{ steps.parameters.outputs.isRC == true }} || ${{ steps.parameters.outputs.isBeta == true }}
         run: |
           version=${{ env.RELEASE_VERSION }}
           git checkout -b release/$version
